### ISSUE TITLE
No entries in any tag

### ISSUE THREAD

**Issue by rschulman** [AkashaProject/Alpha#13] opened 2016-12-27 20:13 UTC
On installation of a new Akasha alpha client (on Mac OS Yosemite) and creation of a new login, the tag search page shows no entries. Selecting a different tag causes the spinning "wait" cursor but ends with same result. Happy to contribute logs but I'm not sure where to locate them.
Screenshot attached.
![akashabug](https://cloud.githubusercontent.com/assets/1304536/21507473/99bb814c-cc46-11e6-8602-1727333fd056.png)

**Comment by bitcloudTheFirst** [comment] 2016-12-30 02:43
Same.

51 entries
No entries

On the same page...

**Comment by MihaiAlisie** [comment] 2017-01-07 11:30
Hi there and thank you for testing AKASHA!

This issue is caused by people publishing something but not waiting enough (~1-5 mins) for the information to be broadcasted into the p2p IPFS network and picked up by other nodes. 

A fix will be introduced in the 0.3.0 release scheduled for next week.

**Comment by SeverS** [comment] 2017-01-16 10:38
This issue is fixed in 0.3.0.
Thanks for reporting 🙇

**Comment by jonathan-soifer** [comment] 2017-01-17 09:58
Maybe close this issue? 😄

**Closed as completed** 2017-01-17 10:23 UTC
